name: ${project.name}
description: ${project.description}
version: ${project.version}

author: arboriginal
website: https://www.spigotmc.org/resources/${spigot-id}
dev-url: https://github.com/arboriginal/${project.artifactId}

main: ${project.groupId}.${project.artifactId}.${spigot-main}
api-version: ${spigot-api}

commands:
  prider-reload:
    description: Reload PlayerRider configuration
    permission: playerrider.reload
    
  prider-toggle:
    description: Toggle own ridability
    permission: playerrider.ducktoggle

permissions:
  playerrider.reload:
      description: Allows to reload the configuration.
      default: op

  playerrider.ride:
    description: Allows to ride a player.
    default: true

  playerrider.ride.keepitem:
    description: Allows to ride a player without consuming the item.
    default: false

  playerrider.whip:
    description: Allows to whip the player you ride.
    default: true

  playerrider.whip.keepitem:
    description: Allows to whip the player you ride without consuming the item.
    default: true

  playerrider.duck:
    description: Allows to be ridden.
    default: true

  playerrider.ducktoggle:
    description: Allows to switch your "ridability".
    default: true

  playerrider.eject:
    description: Allows to eject your passenger.
    default: true
