name: PlayerRider
description: Allow you to ride players.
version: 1.13.2

author: arboriginal
website: https://www.spigotmc.org/resources/playerrider.62799/
dev-url: https://github.com/arboriginal/PlayerRider

depend: [ ]
softdepend: [ ]

api-version: 1.13
database: false

main: me.arboriginal.PlayerRider.PlayerRider

commands:
  prider-reload:
    description: Reload PlayerRider configuration
    permission: playerrider.reload

permissions:
  playerrider.reload:
      description: Allows to reload the configuration.
      default: op

  playerrider.ride:
    description: Allows to ride a player.
    default: true

  playerrider.ride.keepitem:
    description: Allows to ride a player without consuming the item.
    default: false

  playerrider.whip:
    description: Allows to whip the player you ride.
    default: true

  playerrider.whip.keepitem:
    description: Allows to whip the player you ride without consuming the item.
    default: true

  playerrider.duck:
    description: Allows to be ridden.
    default: true

  playerrider.eject:
    description: Allows to eject your passenger.
    default: true
